# Generated by Django 5.0.2 on 2024-04-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_sale_price_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='is_sale',
            new_name='is_sale',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='price',
            new_name='price',
        ),
    ]
